### ISSUE TITLE
Copyright incorrect?

### ISSUE THREAD

**Issue by brentvatne** [keithpops/jeoparty#2]
Maybe this was based off of some skeleton project, but IIRC your name is Keith not Julien ;P

> Copyright (c) 2015 Julien Valéry

**Comment by keithpops** [comment]
Oh you didn't hear I was rebranding? 😛

Started with [web-react](https://github.com/darul75/web-react) which was a little excessive but I'm a sucker for buzz words like `isomorphism` / `universal`.

**Comment by brentvatne** [comment]
;)
